### ISSUE TITLE
[Probably bug] in FontLab macros (AFDKO) autohint.py or BezChar.py

### ISSUE THREAD

**Issue by Arno-Enslin** [adobe-type-tools/afdko#119]
FontLab Studio 5.0.4
Python 2.4
AFDKO build 03-26-2016 (with integrated Python 2.7.10)

The autohint macro is extremely useful, because you can easier hint some glyphs with and others without hint substitution. (Hold the control key, when yo start the autohint macro.) Much more control with the macro than with autohintexe.exe from the command line.

 I am getting the following error:
 
```
Autohinting starting for font Test.otf Thu Mar 31 20:10:36 2016
Hinting F.
	FYI: added flex operators to this character.

Traceback (most recent call last):
  File "<string>", line 879, in ?
  File "<string>", line 873, in run
  File "<string>", line 338, in doHinting
  File "<string>", line 493, in Run_AC
  File "C:\FLStudio\macros\system\modules\BezChar.py", line 408, in MakeGlyphNodesFromBez
    p= Point(x0, y0)
UnboundLocalError: local variable 'x0' referenced before assignment
```
**And this line: > > FYI: added flex operators to this character.**

Looks like the macro tries to generate flex hints. I am not sure. At least there is no option for suppressing flex hint generation. But on the command line you have that option. Shouldn't that option be added to the options panel of the autohint macro?

**Comment by Arno-Enslin** [comment]
Maybe the bug is in autohintexe.exe.

The last autohintexe.exe (which I have), that works without this error in FontLab Studio is the version from AFDKO 2.5 63882. Autohintexe.exe from AFDKO 2.5 64655 does not work anymore with the macro for FontLab Studio.

**Comment by miguelsousa** [comment]
@readroberts the FontLab scripts are now at https://github.com/adobe-type-tools/fontlab-scripts

**Comment by readroberts** [comment]
Fixed. The output of autohintexe changed from using relative to absolute coordinates last year, and the FontLan scripts didn't  cope with these.

**Comment by Arno-Enslin** [comment]
I am still getting the error message:

File "C:\FLStudio 5.0.4\macros\system\modules\BezChar.py", line 408, in MakeGlyphNodesFromBez
    p= Point(x0, y0)
UnboundLocalError: local variable 'x0' referenced before assignment.

And by the way: The folder "modules" is not contained in the public release from 05-24-2016. And it should be a subfolder of the folder "system", shouldn't it?

I was so happy, when I have read, that you have fixed the bug …
